# Site settings
title: Cheng Ji
description: CS&Linguistics Undergraduate at NYU

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /  # set the about page as the root
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Author information
author:
  name: Cheng Ji
  bio: CS&Linguistics Undergraduate at NYU
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/szcharlesji"

# Footer links
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/szcharlesji"

# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: false
#       read_time: false
#       comments: false
#       share: false
#       related: false
#   # _pages
#   - scope:
#       path: "_pages"
#       type: pages
#     values:
#       layout: single
#       author_profile: false

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
